export enum TileProductionMode {
    PRODUCE_SOLDIERS = "PRODUCE_SOLDIERS",
    PRODUCE_BUILDERS = "PRODUCE_BUILDERS",
    PRODUCE_GROWTH = "PRODUCE_GROWTH",
    PRODUCE_INTELLIGENCE = "PRODUCE_INTELLIGENCE",
}
