export enum UserClickMode{ 
    SELECT_TILES = "SELECT_TILES",
    SELECT_ACTION = "SELECT_ACTION",
    SELECT_UNITS = "SELECT_UNITS",
    SELECT_TARGET = "SELECT_TARGET",
    VIEW_TILES = "VIEW_TILES",
}